repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: sort-simple-yaml

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
        # args: [--skip-string-normalization]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        files: "."
        args: [--settings-path=pyproject.toml]
        # args: [--profile, black, --filter-files]

  # - repo: https://github.com/pre-commit/pygrep-hooks
  #   rev: v1.9.0
  #   hooks:
  #     - id: python-check-mock-methods
  #     - id: python-use-type-annotations

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v0.910"
  #   hooks:
  #     - id: mypy
  #       args:
  #         [
  #           --ignore-missing-imports,
  #           --warn-no-return,
  #           --warn-redundant-casts,
  #           --disallow-incomplete-defs,
  #         ]
  #       additional_dependencies: [types-all]

  # - repo: https://github.com/dxa4481/truffleHog.git
  #   rev: v3.68.5
  #   hooks:
  #     - id: trufflehog
  #       args: ["--regex", "--entropy=False"]
